builders:
  data_builder:
    import: "package:data_builder/data_builder.dart"
    builder_factories: [ "dataClassBuilder" ]
    build_extensions: { ".dart": [ ".data.part" ] }
    auto_apply: dependents
    build_to: source
