name: data_builder
description: Data builder is used to create an immutable data class with data_annotation
version: 1.0.0
homepage: https://vegasdevelopments.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  data_annotation: ^1.1.0
  analyzer: ^1.5.0
  build: ^2.0.1
  source_gen: ^1.0.0
  source_helper: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
