name: data_class_builder
description: A starting point for Dart libraries or applications.
version: 1.2.0
homepage: https://vegasdevelopments.com

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.5.0
  build: ^2.0.1
  data_class:
    git: https://github.com/JonathanVegasP/data_class.git
  source_gen: ^1.0.0
  base_exception:
    git: https://github.com/JonathanVegasP/base_exception.git

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
